name: Sync Fork with Upstream

on: 
  schedule: 
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/0rmee/ormee_web.git
          git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout main
          git merge upstream/main --no-edit || echo "Merge conflict, please resolve manually."

      - name: Push Changes
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
