name: Sync Fork with Upstream

on: 
  schedule: 
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/0rmee/ormee_web.git
          git fetch upstream

      - name: Sync All Branches
        run: |
          for branch in $(git branch -r | grep upstream/ | grep -v HEAD | sed 's|upstream/||'); do
            git checkout $branch || git checkout -b $branch
            git merge upstream/$branch --no-edit || echo "Merge conflict on $branch"
            git push origin $branch
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
